output_dir: ${OUTPUT_DIR}

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_3b

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${BASE_MODEL_PATH}/Llama-3.2-3B-Instruct/original/tokenizer.model
  max_seq_len: 8192

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${CHECKPOINT_DIR}
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: ${OUTPUT_DIR}
  model_type: LLAMA3_2
resume_from_checkpoint: False

ref_checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${CHECKPOINT_DIR}
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: ${OUTPUT_DIR}
  model_type: LLAMA3_2


dataset:
  _component_: torchtune.datasets.preference_dataset
  source: json
  data_files: ${DATA_FILE_PATH}
  column_map:
    chosen: messages_chosen
    rejected: messages_rejected
  train_on_input: False
  split: train

seed: null
shuffle: true

batch_size: 1
epochs: 2

optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.05
  lr: 1e-5

lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 10
loss:
  _component_: torchtune.rlhf.loss.DPOLoss
  beta: 0.1
  label_smoothing: 0

max_steps_per_epoch: null
gradient_accumulation_steps: 4

compile: true
device: cuda
dtype: bf16
enable_activation_checkpointing: true
enable_activation_offloading: true

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${OUTPUT_DIR}/logs
log_every_n_steps: 1
log_peak_memory_stats: True

